service: platzi-sls

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: dynamodb:*
          Resource: !GetAtt usersTable.Arn

plugins:
  - serverless-offline
  - serverless-dynamodb-local

package:
  individually: true
  patterns:
    - '!*/**'

functions:
  get-users:
    handler: getUsers/handler.handler
    package:
      patterns:
        - 'getUsers/handler.js'
    events:
      - http:
          path: users/{id}
          method: GET
          # Esto hace requerido el id en la url
          request:
            parameters:
              paths:
                id: true

  create-users:
    handler: createUsers/handler.handler
    package:
      patterns:
        - 'createUsers/handler.js'
    events:
      - http:
          path: users
          method: POST
          #Esto hace validar el body del request con el schema
          request:
            schemas:
              application/json: ${file(schemas/userSchema.json)}

  update-users:
    handler: updateUser/handler.handler
    package:
      patterns:
        - 'updateUser/handler.js'
    events:
      - http:
          path: users/{id}
          method: PATCH
          #Este  request necesita hacer las dos validaciones.
          request:
            parameters:
              paths:
                id: true
            schemas:
              application/json: ${file(schemas/userSchema.json)}

  delete-users:
    handler: deleteUsers/handler.handler
    package:
      patterns:
        - 'deleteUsers/handler.js'
    events:
      - http:
          path: users/{id}
          method: DELETE

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
