service: platzi-sls

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: dynamodb:*
          Resource: !GetAtt usersTable.Arn

plugins:
  - serverless-offline
  - serverless-dynamodb-local

package:
  individually: true
  patterns:
    - '!*/**'

functions:
  get-users:
    handler: getUsers/handler.handler
    package:
      patterns:
        - 'getUsers/handler.js'
    events:
      - http:
          path: users/{id}
          method: GET
  create-users:
    handler: createUsers/handler.handler
    package:
      patterns:
        - 'createUsers/handler.js'
    events:
      - http:
          path: users
          method: POST
  update-users:
    handler: updateUser/handler.handler
    package:
      patterns:
        - 'updateUser/handler.js'
    events:
      - http:
          path: users/{id}
          method: PATCH
  delete-users:
    handler: deleteUsers/handler.handler
    package:
      patterns:
        - 'deleteUsers/handler.js'
    events:
      - http:
          path: users/{id}
          method: DELETE

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
